### ISSUE TITLE
ER-12 not supported 

### ISSUE THREAD

**Issue by Danabw** [mafredri/vyatta-wireguard-installer#10]
Ran script on ER-12 and received following. Can this script be updated to support ER-12, 12P. 

I added a line for e320=e300, and it seemed to work just fine. 

`xxx@xxx:/config/scripts/post-config.d$ ./wireguard.sh help
Unsupported board e302, aborting.`

**Comment by Danabw** [comment]
Fyi, I added a line to the script (e302=e300) and everything seemed to install just fine.

**Comment by mafredri** [comment]
Thanks for reporting @Danabw! It's been tough trying to find all board revisions. I'd be happy to accept a PR if you care to submit one or I can add them if you can clarify if it's just `e302` or both `e302` and `e320`?

**Comment by Danabw** [comment]
Hi, thanks for the response. 
Apologies, but I can only confirm ER12 = e302 as that's the router I own/use.  I'm afraid I don't have any other information on board revisions. 

Wish I could be of more help. I'm an occassional user of GitHub and have never done a PR, so probably better that I don't do something where I might mess things up.  <eek>  :)

**Comment by mafredri** [comment]
No need to apologize, I appreciate you confirming the one. And I don’t think you’d mess anything up, so if you’re feeling adventurous I’d be more than happy to accept your first PR 😊! But truly, no pressure!

**Comment by mafredri** [comment]
I went ahead and added this now, thanks again for reporting!
