### ISSUE TITLE
Upgrade option - unable to resolve host 

### ISSUE THREAD

**Issue by Danabw** [mafredri/vyatta-wireguard-installer#17]
FYI, tried the script using the upgrade option and it was unable to complete the download. Let me know if you'd like me to test anything! Thanks. 

`xxx@xxx:/config/scripts/post-config.d$ ./wireguard.sh upgrade
Upgrading WireGuard...
Checking latest release for v2.0-e300...
Downloading null...
curl: (6) Could not resolve host: null
xxx@xxx:/config/scripts/post-config.d$
`

**Comment by mafredri** [comment]
It looks like you're using an old version of the script, you could try running `self-update` and then trying the upgrade again.

**Comment by Danabw** [comment]
DOH! Sorry, was setting up a new pi last night at the same time and lost track of what I'd done, in which window. That's exactly it, operator error. Updated script and then updated Wireguard, and everything works as expected. As they say, move along, nothing to see here... ;-)
