### ISSUE TITLE
rmmod during upgrade

### ISSUE THREAD

**Issue by ruimarinho** [mafredri/vyatta-wireguard-installer#2]
According to https://github.com/Lochnair/vyatta-wireguard/issues/72#issuecomment-423840448, the module should be removed first during an upgrade.

Have you considered this? Thanks.

**Comment by mafredri** [comment]
I believe `modprobe -r` should have the same effect, which were doing here: https://github.com/mafredri/vyatta-wireguard-installer/blob/master/wireguard.sh#L68

Did you run into any problems?
