### ISSUE TITLE
It doesn't seem to work for me on my Edgerouter X.

### ISSUE THREAD

**Issue by BrianG61UK** [mafredri/vyatta-wireguard-installer#20]
When I try to upgrade the wireguard on my Edgerouter X this is what happens:
```
admin@ubnt:~$
admin@ubnt:~$
admin@ubnt:~$
admin@ubnt:~$ sudo /config/scripts/post-config.d/wireguard.sh upgrade
Upgrading WireGuard...
Checking latest release for e50-v2...
Downloading e50-v2-v1.0.20200520-v1.0.20200513.deb...
Disabling wg0...
The specified configuration node already exists
[ interfaces wireguard wg0 address 192.168.213.1/24 ]
RTNETLINK answers: Cannot assign requested address

Commit failed
admin@ubnt:~$ show version all
Version:      v2.0.8-hotfix.1
Build ID:     5278088
Build on:     03/05/20 16:41
Copyright:    2012-2019 Ubiquiti Networks, Inc.
HW model:     EdgeRouter X 5-Port
HW S/N:       18E829ADC776
Uptime:       20:41:47 up 1 day, 20:53,  1 user,  load average: 1.21, 1.13, 1.04

Aii wireguard                 1.0.20200506-2
admin@ubnt:~$

```

**Comment by mafredri** [comment]
What does your current (active) WireGuard configuration look like (`show interfaces wireguard`, feel free to sensor your keys)?

A reboot might help too.

**Comment by mafredri** [comment]
Actually, I just noticed you are using `sudo` for the script, so the issue here is probably fixed by #16 but it won't work until those permissions issues are fixed by a reboot (or manually if you know how to, I don't).

**Comment by BrianG61UK** [comment]
Sorry, the sudo was just because I tried without it first then tried with sudo to see if that would make it work.

Here is some info about my connfiguration:
```
admin@ubnt:~$
admin@ubnt:~$
admin@ubnt:~$ show interfaces wireguard
Codes: S - State, L - Link, u - Up, D - Down, A - Admin Down
Interface    IP Address                        S/L  Description
---------    ----------                        ---  -----------
wg0          192.168.213.1/24                  u/u  WireGuard Server
             2a02:8010:66b7:eeee::1/64
admin@ubnt:~$
admin@ubnt:~$ show configuration commands | egrep wireguard
set interfaces wireguard wg0 address 192.168.213.1/24
set interfaces wireguard wg0 address '2a02:8010:66b7:eeee::1/64'
set interfaces wireguard wg0 description 'WireGuard Server'
set interfaces wireguard wg0 listen-port 62793
set interfaces wireguard wg0 mtu 1420
set interfaces wireguard wg0 peer 1111111111111111111111111111111111111111111= allowed-ips 192.168.213.201/32
set interfaces wireguard wg0 peer 1111111111111111111111111111111111111111111= allowed-ips '2a02:8010:66b7:eeee:3d7b:ef02:6520:201/128'
set interfaces wireguard wg0 peer 1111111111111111111111111111111111111111111= description 'WireGuard Client 1'
set interfaces wireguard wg0 peer 2222222222222222222222222222222222222222222= allowed-ips 192.168.213.202/32
set interfaces wireguard wg0 peer 2222222222222222222222222222222222222222222= allowed-ips '2a02:8010:66b7:eeee:3d7b:ef02:6520:202/128'
set interfaces wireguard wg0 peer 2222222222222222222222222222222222222222222= description 'WireGuard Client 2'
set interfaces wireguard wg0 peer 3333333333333333333333333333333333333333333= allowed-ips 192.168.213.203/32
set interfaces wireguard wg0 peer 3333333333333333333333333333333333333333333= allowed-ips '2a02:8010:66b7:eeee:3d7b:ef02:6520:203/128'
set interfaces wireguard wg0 peer 3333333333333333333333333333333333333333333= description 'WireGuard Client 3'
set interfaces wireguard wg0 private-key PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP=
set interfaces wireguard wg0 route-allowed-ips true
admin@ubnt:~$
admin@ubnt:~$

```

**Comment by BrianG61UK** [comment]
Sorry, sudo is just there because I tried both without sudo and with sudo.

Here is some info about my configuration (port number, encryption keys and public IPv6 addresses are obfuscated):
```
admin@ubnt:~$
admin@ubnt:~$
admin@ubnt:~$ show interfaces wireguard
Codes: S - State, L - Link, u - Up, D - Down, A - Admin Down
Interface    IP Address                        S/L  Description
---------    ----------                        ---  -----------
wg0          192.168.213.1/24                  u/u  WireGuard Server
             2001:db8:1234:eeee::1/64
admin@ubnt:~$
admin@ubnt:~$ show configuration commands | egrep wireguard
set interfaces wireguard wg0 address 192.168.213.1/24
set interfaces wireguard wg0 address '2001:db8:1234:eeee::1/64'
set interfaces wireguard wg0 description 'WireGuard Server'
set interfaces wireguard wg0 listen-port 65432
set interfaces wireguard wg0 mtu 1420
set interfaces wireguard wg0 peer 1111111111111111111111111111111111111111111= allowed-ips 192.168.213.201/32
set interfaces wireguard wg0 peer 1111111111111111111111111111111111111111111= allowed-ips '2001:db8:1234:eeee:3d7b:ef02:6520:201/128'
set interfaces wireguard wg0 peer 1111111111111111111111111111111111111111111= description 'WireGuard Client 1'
set interfaces wireguard wg0 peer 2222222222222222222222222222222222222222222= allowed-ips 192.168.213.202/32
set interfaces wireguard wg0 peer 2222222222222222222222222222222222222222222= allowed-ips '2001:db8:1234:eeee:3d7b:ef02:6520:202/128'
set interfaces wireguard wg0 peer 2222222222222222222222222222222222222222222= description 'WireGuard Client 2'
set interfaces wireguard wg0 peer 3333333333333333333333333333333333333333333= allowed-ips 192.168.213.203/32
set interfaces wireguard wg0 peer 3333333333333333333333333333333333333333333= allowed-ips '2001:db8:1234:eeee:3d7b:ef02:6520:203/128'
set interfaces wireguard wg0 peer 3333333333333333333333333333333333333333333= description 'WireGuard Client 3'
set interfaces wireguard wg0 private-key PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP=
set interfaces wireguard wg0 route-allowed-ips true
admin@ubnt:~$
admin@ubnt:~$
```

**Comment by BrianG61UK** [comment]
We're now also discussing this [here](https://community.ui.com/questions/Release-WireGuard-for-EdgeRouter/3765d2a4-1952-4629-948a-3ac9d9c22311#answer/420d9c62-8867-4c95-999c-d9982a27a1fd)

**Comment by mafredri** [comment]
Thanks for linking the thread @BrianG61UK. Judging from what I've read there I'm starting to suspect it's the use of both IPv4 and IPv6 that's causing issues here. Like karog mentioned the order in which things happen is important and using IPv6 is probably an edge case that has not been tested with the template/node definitions provided by the WireGuard package.

There's an ongoing issue in the official repo about rewriting the template logic: https://github.com/WireGuard/wireguard-vyatta-ubnt/issues/20. There's also some interesting discussions being had in https://github.com/WireGuard/wireguard-vyatta-ubnt/pull/14.

**Comment by mafredri** [comment]
@BrianG61UK if you want to test the theory, you could `configure`, delete the IPv6 `address` from `wg0` and from `peers -> allowed-ips`, `commit` (no need to save). Then run `upgrade` and 🤞 it should come out alright (config will be restored from last save by the script).

(Make sure the script is up-to-date too, via `self-update`.)

**Comment by BrianG61UK** [comment]
> @BrianG61UK if you want to test the theory, you could `configure`, delete the IPv6 `address` from `wg0` and from `peers -> allowed-ips`, `commit` (no need to save). Then run `upgrade` and crossed_fingers it should come out alright (config will be restored from last save by the script).

I can't even make it work for a manual update. Messing with the configuration of wg0 seems to get the router into a state where the only way to get it running the original configuration is to reboot.
load followed by commit just produces weird errors.

**Comment by mafredri** [comment]
Did you try the manual configure steps to delete the IPv6 addresses I suggested? By doing those, followed by an upgrade via the script, what essentially happens is:

1. IPv6 addresses are deleted and committed
2. Script sets route allowed IPs to false and commits
3. Script deletes wireguard interface and commits
4. The package is upgraded
5. Script loads configuration and commits

My hunch is that things need to happen in this exact order, and they _may_ work.

**Comment by BrianG61UK** [comment]
It refuses to commit after I've deleted the IPv6 addresses.

**Comment by BrianG61UK** [comment]
See also my issue here: https://github.com/WireGuard/wireguard-vyatta-ubnt/issues/35
