### ISSUE TITLE
Documentation for configuring a USG-PRO 4 for client VPN access

### ISSUE THREAD

**Issue by G400** [mafredri/vyatta-wireguard-installer#25]
Where can I find documentation for configuring a USG-PRO 4 for client VPN access?

**Comment by mafredri** [comment]
Hey, this repo is only for the script to help manage the installation, not for configuration. That said, I’m not aware of any such documentation and haven’t tried setting it up myself.

You may want to check the official package issue tracker if it’s come up: https://github.com/WireGuard/wireguard-vyatta-ubnt/

**Comment by G400** [comment]
Thank you mafredri!
I was hoping that someone had picked up you excellent work and documented how to enable and configure client VPN access using Wireguard.
Nice background picture! 
Is it from Norway?
