### ISSUE TITLE
Module wireguard not found

### ISSUE THREAD

**Issue by bswinnerton** [mafredri/vyatta-wireguard-installer#4]
Hi there 👋,

Thank you for putting this repo together. When trying to run the script for the first time, on an ER-X which has never had Wireguard installed, I ran into the following:

```
ubnt@ubnt:/config/scripts/post-config.d$ ./wireguard.sh install
Installing WireGuard...
Checking latest release for e50...
Downloading wireguard-e50-0.0.20190406-1.deb...
Installing wireguard-e50-0.0.20190406-1.deb...
Selecting previously unselected package wireguard.
(Reading database ... 37023 files and directories currently installed.)
Preparing to unpack .../wireguard-e50-0.0.20190406-1.deb ...
Adding 'diversion of /opt/vyatta/share/perl5/Vyatta/Interface.pm to /opt/vyatta/share/perl5/Vyatta/Interface.pm.vyatta by wireguard'
Adding 'diversion of /opt/vyatta/share/vyatta-cfg/templates/firewall/options/mss-clamp/interface-type/node.def to /opt/vyatta/share/vyatta-cfg/
templates/firewall/options/mss-clamp/interface-type/node.def.vyatta by wireguard'
Unpacking wireguard (0.0.20190406-1) ...
Setting up wireguard (0.0.20190406-1) ...
modprobe: FATAL: Module wireguard not found in directory /lib/modules/4.14.54-UBNT
```

Which I suspect is coming from this line:

https://github.com/mafredri/vyatta-wireguard-installer/blob/5e6f2f2c87f70ce06f9c3e186eba566bfaf7cf09/wireguard.sh#L95

But I'm not sure it's this script or the actual `.deb` that's not properly installing WireGuard.

And separately, when trying to subsequently remove wireguard, the following is returned:

```
ubnt@ubnt:/config/scripts/post-config.d$ ./wireguard.sh remove
Removing WireGuard...
Disabling ...
The specified configuration node is not valid
Set failed
```

Perhaps the order of the `remove` function should be shuffled around to ensure that wireguard is purged from `dkpg` so that `is_installed` returns an appropriate value?

https://github.com/mafredri/vyatta-wireguard-installer/blob/5e6f2f2c87f70ce06f9c3e186eba566bfaf7cf09/wireguard.sh#L210

Happy to put together a PR to move those around if you think this is a wise idea.

**Comment by bswinnerton** [comment]
I see the problem. The script automatically pulls the non-`v2.0` deb package, which causes problems when the system image is at `v2.x`. Ideally therer would be some logic to determine what the current system image is and find the appropriate wireguard version. I believe this can be determined with `show system image`.

**Comment by mafredri** [comment]
Hi, thanks for reporting and investigating, and sorry you ran into this. It's a known issue that the current script doesn't support `v2.0` downloads, but I don't actually have an EdgeRouter to test with myself.

I'd love to get this fixed though, and `show system image` seems like it could work. But then I just realized the modules are always compiled for a specific kernel, so maybe we could get away with comparing against `uname -r`?

For an immediate remedy, you could change this line:

https://github.com/mafredri/vyatta-wireguard-installer/blob/5e6f2f2c87f70ce06f9c3e186eba566bfaf7cf09/wireguard.sh#L6

To `[e50]=v2.0-e50` and the script should work.

**Comment by mafredri** [comment]
Actually, this should be fixed on `master`. We'll have to see if we need more fine-grained detection or not but should work for now 😅.
