### ISSUE TITLE
Upgrade from EdgeOS 1.10.5 to 2.0.6 causes problem

### ISSUE THREAD

**Issue by sslupsky** [mafredri/vyatta-wireguard-installer#6]
I think there may be a problem with the upgrade to v2.  I ran the script to upgrade WireGuard when still running EdgeOS 1.10.5.  That ran properly after I fixed the interfaces issue and wg came back up.  I then did the upgrade to EdgeOS v2.0.6.  Now, the WireGuard interfaces do not come up.  I think this is because the proper version of WireGuard is not installed.  So, i did another upgrade.  This time, the upgrade shows:
```
Upgrading WireGuard...
Checking latest release for v2.0-e200...
WireGuard is already up to date (0.0.20190702-1), nothing to do.
```

However, when I look in the cache directory, this is what is there:
```
-rw-r--r--    1 sslupsky vyattacf    198426 Aug  7 09:46 wireguard-e200-0.0.20190702-1.deb
```

Which is not the correct version.

**Comment by sslupsky** [comment]
I put the correct version into the cache directory and removed the old version.  The check still fails and I see the same "already up to date" message.

**Comment by sslupsky** [comment]
Probably need to do this check:
https://github.com/mafredri/vyatta-wireguard-installer/blob/0a7260d5c9ca450a2c64fac9d72bda1f1e9903fe/wireguard.sh#L288
again when doing the version check.

**Comment by mafredri** [comment]
Hmm, you seem to be hitting all the edge cases, sorry about that. I don't have an EdgeRouter so haven't been able to really test these v1/v2 scenarios. I'll try to look at this a bit later. In the meanwhile, what does `dpkg -l "*wireguard*"` show?

**Comment by mafredri** [comment]
I _think_ the problem is that the v1 `deb` allows itself to be installed on v2.0, whereas if it didn't we wouldn't have this issue. But we can probably work around it 😄.

**Comment by sslupsky** [comment]
dpkg -l "*wireguard* returns:
```
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                               Version                Architecture           Description
+++-==================================-======================-======================-=========================================================================
ii  wireguard                          0.0.20190702-1         mips                   fast, modern, secure kernel VPN tunnel
```

Note:  I did a manual update and v2 is now loading and running.
