### ISSUE TITLE
Push new versions of the script as a "release" on GitHub

### ISSUE THREAD

**Issue by ghost** [mafredri/vyatta-wireguard-installer#7]
This will make it easier to monitor when new versions of the script gets released using something like GitPunch or GitHubs built in function.

**Comment by mafredri** [comment]
Thanks, it's a good suggestion, I'll keep it in mind going forward.

**Comment by mafredri** [comment]
@broizter it's been a while, but it's finally here: https://github.com/mafredri/vyatta-wireguard-installer/releases/tag/v1.0.0.
