### ISSUE TITLE
Change repo to active maintained fork

### ISSUE THREAD

**Issue by yubiuser** [mafredri/vyatta-wireguard-installer#8]
Thanks for providing this script.

You're using the repo provided by Lochnair to get the latest wireguard build. Some days ago Lochnair has announced that the will [no longer actively maintain this project](https://github.com/Lochnair/vyatta-wireguard/issues/140#issuecomment-587031573).  Could you please change the repo to an actively maintained fork (e.g. by [FossorsLP](https://github.com/FossoresLP/vyatta-wireguard/releases))?

Thanks.

**Comment by mafredri** [comment]
Hey, thanks for bringing this to my attention @yubiuser, I've only been watching releases of Lochnair's repo. I'll take this under consideration and do some testing 👍.

**Comment by yubiuser** [comment]
Thanks.

I changed the relevant line to

`curl -sSL https://api.github.com/repos/FossoresLP/vyatta-wireguard/releases \`

and it worked perfectly. But of course you're free to use any other repo.

**Comment by nickray** [comment]
https://github.com/WireGuard/wireguard-vyatta-ubnt

**Comment by mafredri** [comment]
@nickray already tracked in #11, I'll try to get around to it today.
